# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Locale
      run: |
        sudo apt-get -y install fonts-ipafont language-pack-ja
        sudo update-locale LANG=ja_JP.UTF-8
        sudo update-locale LC_ALL=ja_JP.UTF-8
    - name: Set up Time-Zone
      run: sudo timedatectl set-timezone Asia/Tokyo
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      run: mvn -B clean verify -Dgpg.skip=true
